### PR TITLE
Fix hardcoded chain/asset unitvalues

### LINKED ISSUE #19: Use unitValue from config.json file for each asset instead of hardcoded value
The `div` property https://github.com/Leasehold/ldex-ui/pull/18/files#diff-8d1dfa6a15e3dd0647fc1f2a673dcc2aR344 is hardcoded.
It's also hardcoded when calculating the balance here https://github.com/Leasehold/ldex-ui/pull/18/files#diff-8d1dfa6a15e3dd0647fc1f2a673dcc2aR333

This number depends on the asset so it should come from the `config.json` file; from the `unitValue` property.

### PR DESCRIPTION
**Pull request by sacOO7**
- Added singleton function/class to store chains/assets config,
- Extracted asset balance calculation into separate utils method from all files (Applying DRY)
- Fixes #19

### CODE REVIEW

**Comment by sacOO7** [comment]
Need to check if decimal values are configured from json file. Currently decimal values are hardcoded in following functions (Utils.js) 
- getNumericAssetBalance
- getLiteralAssetBalance

**Comment by sacOO7** [comment]
Also https://github.com/Leasehold/ldex-ui/blob/34d9a399369667b831636879ac3997745e59270b/lisk-dex-electron/src/App.jsx#L243

Can we remove this hardcoded value?

File: lisk-dex-electron/src/Utils.js [hunk 1]
```diff
@@ -1,3 +1,35 @@
...
+      assetConfig = assets;
+    },
+    getUnitValue(assetName) {
+      return assetConfig[assetName] && assetConfig[assetName].unitValue;
+    },
+  };
+})();
+
+// returns number
+const getNumericAssetBalance = (assetAmount, assetName, decimal = 2) => {
```
Comment (sacOO7) [inline lisk-dex-electron/src/Utils.js:95]: @jondubois can we read this decimal value from config.

File: lisk-dex-electron/src/Utils.js [hunk 2]
```diff
@@ -1,3 +1,35 @@
...
+  // eslint-disable-next-line no-restricted-properties
+  const uptoDecimalPlaces = Math.pow(10, decimal);
+  const unitValue = CryptoAsset.getUnitValue(assetName);
+  return Math.round((assetAmount * uptoDecimalPlaces) / unitValue) / uptoDecimalPlaces;
+};
+
+// returns string
+const getLiteralAssetBalance = (assetAmount, assetName, decimals = 4) => {
```
Comment (sacOO7) [inline lisk-dex-electron/src/Utils.js:103]: @jondubois same for this decimal value

File: lisk-dex-electron/src/Utils.js [hunk 3]
```diff
@@ -1,3 +1,35 @@
+// Eventually store all config in singleton class and make it accessible everywhere
+const CryptoAsset = (() => {
```
Comment (jondubois) [inline lisk-dex-electron/src/Utils.js]: Good idea to have the config as an instance with some convenience methods but it would be better to have a single config object for all configs (not a separate one for assets); it's easier to manage and make sense of the code if there is only one config object in the whole app.

The method `getUnitValue(assetName)` could be renamed to `getAssetUnitValue(assetName)`.

This object could be renamed to just `Config` or `Configuration` and it can be returned by the `processConfiguration` function. For the tests, it can be constructed manually without the `processConfiguration` function.

**Review by jondubois — CHANGES_REQUESTED** [review]

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 4]
```diff
@@ -91,15 +94,12 @@ export default class PlaceOrder extends React.Component {
 
   getEstimatedReturnsBreakDown(estimate) {
     let verboseEstimation = `${estimate.estimatedReturns.toFixed(4)} ${estimate.assetExchanged}`;
-    const statuses = [];
-    if (estimate.status === EstimationStatus.PARTIAL_MATCH || estimate.amountYetToBeSold > 0) {
+    if (estimate.status === EstimationStatus.NO_MATCH || EstimationStatus.PARTIAL_MATCH) {
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: I think it's meant to be:

```
if (estimate.status === EstimationStatus.NO_MATCH || estimate.status === EstimationStatus.PARTIAL_MATCH) {
```

**Review by jondubois — CHANGES_REQUESTED** [review]

File: lisk-dex-electron/src/Utils.js (hunk 3 above)
Comment (sacOO7) [reply lisk-dex-electron/src/Utils.js]: Will be moving ```Configuration``` to ```processConfiguration``` as a part of next PR (it's on top of current one to make review easy)

File: lisk-dex-electron/src/Utils.js (hunk 1 above)
Comment (sacOO7) [reply lisk-dex-electron/src/Utils.js:95]: @jondubois need inputs on this one

File: lisk-dex-electron/src/Utils.js (hunk 2 above)
Comment (sacOO7) [reply lisk-dex-electron/src/Utils.js:103]: @jondubois need inputs on this one

**Review by jondubois — APPROVED** [review]
