### PR TITLE
Validate order

### LINKED ISSUE #10: Also check sufficient balance before sending a tx
image

The sell window checks is the amount is => than the minimum amount of LSH. But not if there's sufficient balance on the users account. Only after it sends a tx, which will fail, it shows the insufficient balance message.

### PR DESCRIPTION
**Pull request by sacOO7**
- Refactored place order validation
- Added number validation for input
- Added check for amount wrt balance before placing limit and market order
- Fixes #10

### CODE REVIEW

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 1]
```diff
@@ -136,7 +136,13 @@ export default class PlaceOrder extends React.Component {
       price: null,
       amount: null,
     };
-    if (!this.state.marketMode) {
+    if (Number.isNaN(this.state.amount) || this.state.amount === '') {
+      errors.amount = 'The order amount must be a number.';
+      success = false;
+    } else if (this.state.amount > this.props.assetBalance) {
+      errors.amount = 'Insufficient balance !!';
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: A single `!` looks cleaner. Also there should be no space between `balance` and `!`.

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 2]
```diff
@@ -380,7 +382,7 @@ export default class PlaceOrder extends React.Component {
                 <br />
                 {this.state.errors.price && <div className="error-message">{this.state.errors.price}</div>}
                 <div className="price-container">
-                  <input name="price" className="order-val-input" type="text" title="Decimal number" value={this.state.price} onChange={this.handleChange} />
+                  <input name="price" className="order-val-input" type="number" title="Decimal number" value={this.state.price} onChange={this.handleChange} />
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: This was a text input on purpose because the number input didn't work great on mobile devices and the increment/decrement buttons were not necessary.

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 3]
```diff
@@ -390,7 +392,7 @@ export default class PlaceOrder extends React.Component {
             <br />
             {this.state.errors.amount && <div className="error-message">{this.state.errors.amount}</div>}
             <div className="amount-container">
-              <input name="amount" className="order-val-input" type="text" title="Decimal number" value={this.state.amount} onChange={this.handleChange} />
+              <input name="amount" className="order-val-input" type="number" title="Decimal number" value={this.state.amount} onChange={this.handleChange} />
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: Same here. Text input is simpler.

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 1 above)
Comment (jondubois) [reply lisk-dex-electron/src/PlaceOrder.jsx]: You need to account for the transaction fee as well. If your balance is 1000 and you try to send 1000, it should reject because you also need to pay 0.1 LSK transaction fee. The base transaction fee depends on the market. Look for `exchangeFeeBase` from the `/status` endpoint.

**Review by jondubois — CHANGES_REQUESTED** [review]

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 2 above)
Comment (jondubois) [reply lisk-dex-electron/src/PlaceOrder.jsx]: The issue was raised in the early repo here: https://github.com/Jaxkr/lisk-dex-ui/issues/3

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 1 above)
Comment (sacOO7) [reply lisk-dex-electron/src/PlaceOrder.jsx]: Regarding this. shouldn't it be, the fee should be deducted from the amount being sent? I have seen same kind of behaviour on most of the exchanges. We can probably adjust for fee in estimated received value.

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 4]
```diff
@@ -29,10 +29,12 @@ export default class PlaceOrder extends React.Component {
     const { target } = event;
     const value = target.type === 'checkbox' ? target.checked : target.value;
     const { name } = target;
-
-    this.setState({
-      [name]: value,
-    });
+    const isNumber = value === '' || /^-?[\d.]+(?:e-?\d+)?$/.test(value);
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: This RegExp has some problems. It will say that `123.234.34` (with two dots) is a number. Also, we should not allow negative numbers in this case.

On the DEX back end, this RegExp is used:

`/^([0-9]+\.?|[0-9]*\.[0-9]+)$/`

It allows a positive number with or without decimal. It allows ending the number with a dot like `10.` or starting with a dot like `.2` but JavaScript also allows both of these cases.

**Review by jondubois — CHANGES_REQUESTED** [review]
About the fee, the DEX is not completely like a regular exchange because centralized exchanges only have a percentage (%) fee whereas the DEX has both % fee and also a base fee which for the LSK/LSH market is 0.1 LSK/LSH (to cover blockchain transaction fees on either chain).

If the fee was just a % of the total like a centralized exchange, then you would be right, the front end would not have to consider it, but because with DEX, there is also a flat base fee, it needs to be factored in as part of the validation. The user shouldn't have to wait to submit their transaction before they find out that they don't have enough funds.

If your account has 100 LSK and you try to submit an order of size 100 LSK, the blockchain will refuse your transaction because you won't be able to cover the 0.1 LSK flat blockchain fee. The front end should prevent this. You need to use the `exchangeFeeBase` (but you need to divide this number by `unitValue` from the `ldex-ui` config to get the unit value in LSK or LSH).

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 4 above)
Comment (jondubois) [reply lisk-dex-electron/src/PlaceOrder.jsx]: We could also use `/^([\d]+\.?|[\d]*\.[\d]+)$/`

**Comment by sacOO7** [comment]
I have added base fee validation before submitting order. Still testing on the local, if everything is working fine.

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 5]
```diff
@@ -126,42 +129,43 @@ export default class PlaceOrder extends React.Component {
...
     if (Number.isNaN(this.state.amount) || this.state.amount === '') {
       errors.amount = 'The order amount must be a number.';
       success = false;
-    } else {
-      const amount = parseFloat(this.state.amount);
-      if (amount < minOrderAmount) {
-        errors.amount = `The specified amount was less than the minimum order amount allowed by this DEX market which is ${
-          minOrderAmount
-        } ${sourceAsset.toUpperCase()}.`;
+    } else if (amount > actualAssetBalance) {
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: There is something wrong with this logic somewhere because the red error message `The specified amount was less than the minimum order amount allowed by this DEX market which is 10 LSK.` no longer comes up when placing a limit order (it only shows up when placing a market order).

To reproduce, log into a wallet, then place a limit order, type `5` as the amount and submit, the error message does not show up.

**Review by jondubois — CHANGES_REQUESTED** [review]

**Comment by sacOO7** [comment]
Ah .. ok, I will look into it .

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 5 above)
Comment (sacOO7) [reply lisk-dex-electron/src/PlaceOrder.jsx]: Seems it was default IDE refactoring, I thought it was an intelligent refactoring - swap of if else conditions
I will fix and push right away

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 6]
```diff
@@ -318,6 +329,23 @@ export default class PlaceOrder extends React.Component {
...
+
+  getBaseFee() {
+    const dexConfig = this.props.configuration.markets[this.props.activeMarket].marketOptions;
+    const chains = Object.keys(dexConfig.chains);
+    const firstChain = dexConfig.chains[chains[0]];
+    const secondChain = dexConfig.chains[chains[1]];
+    const baseFeeKey = 'exchangeFeeBase';
+    const keyDescriptor = marketInfoDescriptor[baseFeeKey];
+    const firstChainBaseFee = firstChain[baseFeeKey] / keyDescriptor.div;
+    const secondChainBaseFee = secondChain[baseFeeKey] / keyDescriptor.div;
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx:345]: The `div` value should come from the `config.json` file because it is configurable https://github.com/Leasehold/ldex-ui/blob/master/lisk-dex-electron/public/config.json#L13

It's important that all the important info about any market comes from only two places:

- The `config.json` file
- The `/status` HTTP API endpoint

Inside `Market.js`, the `div` property for `minOrderAmount`, `minPartialTake`, `exchangeFeeBase` should not be there since this value depends on the market so it cannot be hardcoded.

**Review by jondubois — CHANGES_REQUESTED** [review]

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 7]
```diff
@@ -318,6 +329,23 @@ export default class PlaceOrder extends React.Component {
     }
   }
 
+  getAssetBalance() {
+    const whole = 10 ** 8;
+    return Math.round((this.props.assetBalance * 100) / whole) / 100;
+  }
+
+  getBaseFee() {
```
Comment (jondubois) [inline lisk-dex-electron/src/PlaceOrder.jsx]: Maybe it should be plural `getBaseFees` since it returns fees for two chains.

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 6 above)
Comment (sacOO7) [reply lisk-dex-electron/src/PlaceOrder.jsx:345]: Ohk... actually those values were hardcoded in the code itself, I moved them to market.js

Comment (sacOO7) [reply lisk-dex-electron/src/PlaceOrder.jsx:345]: Didn't know I can actually get them from config.json, will make then necessary change

Comment (sacOO7) [reply lisk-dex-electron/src/PlaceOrder.jsx:345]: Can we create a new issue for this one? I think impact will be at several places.

File: lisk-dex-electron/src/PlaceOrder.jsx [hunk 8]
```diff
@@ -318,6 +329,23 @@ export default class PlaceOrder extends React.Component {
     }
   }
 
+  getAssetBalance() {
+    const whole = 10 ** 8;
+    return Math.round((this.props.assetBalance * 100) / whole) / 100;
```
Comment (sacOO7) [inline lisk-dex-electron/src/PlaceOrder.jsx:334]: @jondubois Also about the getAssetBalance function, isn't 10 ** 8 also supposed to come from config.json?

Comment (jondubois) [reply lisk-dex-electron/src/PlaceOrder.jsx:334]: Ah yes it is. I missed that one.

**Review by jondubois — APPROVED** [review]
OK, let's do the units as a separate issue since it affects balance too.

File: lisk-dex-electron/src/PlaceOrder.jsx (hunk 8 above)
Comment (sacOO7) [reply lisk-dex-electron/src/PlaceOrder.jsx:334]: Btw. why do we multiply by 100 and then divide by 100 again

Comment (jondubois) [reply lisk-dex-electron/src/PlaceOrder.jsx:334]: This is an efficient way to round to 2 decimal places.
